### PR TITLE
Seperating workflows, using config from reference for regression testing

### PR DESCRIPTION
**Pull request by v1kko**

### CODE REVIEW

**Comment by v1kko** [comment]
I removed the analytic tests from the regression workflow, maybe it is better to add them as a test  in the ref_outputs dir, otherwise we will have to decide where to re-add the analytic tests.

**Comment by d-cogswell** [comment]
@lightningclaw001 Debbie, when you get the chance can you test Victor's solution here to run regression tests from the folders in ref_outputs?

**Comment by d-cogswell** [comment]
Hey @v1kko , I'm a little confused about what this pull request is doing. What is the difference between the two github workflows? Also, it looks to me like run_tests.py is still pulling test definitions from the functions in test_defs.py?

**Comment by v1kko** [comment]
Hi @d-cogswell , 
the regression worklow does not use run_tests.py anymore,
the pull request workflow does, but I think it can be deleted, as it only compares the tests (in test_defs.py) for the base and modified branch

**Pull request closed without merging**
